# Generated by Django 5.0.7 on 2024-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='about_user',
            field=models.CharField(max_length=10000),
        ),
    ]
