# Generated by Django 5.0.7 on 2024-09-03 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userinformation_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
