# Generated by Django 5.0.7 on 2024-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_created_at_item_end_time_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
