# Generated by Django 5.0.7 on 2024-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userinformation_about_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
