# Generated by Django 5.0.7 on 2024-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_bid',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
