# Generated by Django 5.0.7 on 2024-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bid',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
        ),
    ]
