# Generated by Django 5.0.7 on 2024-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
