# Generated by Django 5.0.7 on 2024-09-14 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userinformation_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidder',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='items_for_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
