# Generated by Django 5.0.7 on 2024-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_item_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
